/*
389. Find the Difference
Solved
Easy
Topics
premium lock icon
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        
        char resultCharacter = 0;
        
        // XOR all characters from string s
        for (int index = 0; index < s.length(); index++) {
            resultCharacter ^= s.charAt(index);
        }
        
        // XOR all characters from string t
        for (int index = 0; index < t.length(); index++) {
            resultCharacter ^= t.charAt(index);
        }
        
        return resultCharacter;
    }
}
